name: V8-Auto-Task
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
    - cron: "0 14 * * *"
    - cron: "0 17 * * *"
    - cron: "0 20 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python main.py
      
